algorithm: priorities
agents:
  - type: solar
    AC: 900
    DC: 1000
    orientation: EW
  - type: solar
    AC: 500
    DC: 550
    orientation: S
  - type: demand
    scale: 1
    profile: Farm
  - type: demand
    scale: 1
    profile: RealEstate
  - type: battery
    energy_capacity: 2000
    power: 1000
  - type: battery
    energy_capacity: 1000
    power: 750
grid:
  name: Grid
