algorithm: Priorities
agents:
  - type: solar
    AC: 9000
    DC: 10000
    orientation: EW
  - type: solar
    AC: 5000
    DC: 5500
    orientation: S
  - type: wind
    location: Onshore
    power: 1000
  - type: demand
    scale: 4.5
    profile: Farm
  - type: demand
    scale: 6
    profile: RealEstate
  - type: battery
    energy_capacity: 2000
    power: 1000
  - type: battery
    energy_capacity: 1000
    power: 750
grid:
  name: Grid
