algorithm: Priorities
chunk_size: 1000
training_steps: 20000
num_initial_random_steps: 500
update_interval: 50
horizon: 16
batch_size: 32
update_steps: 1
agents:
  # - type: solar
  #   AC: 9000
  #   DC: 10000
  #   orientation: S
  - type: solar
    AC: 2000
    DC: 2000
    orientation: EW
  - type: solar
    AC: 1000
    DC: 1000
    orientation: EW
  # - type: wind
  #   location: Onshore
  #   power: 1000
  #   AC: 900
  - type: demand
    scale: 15
    profile: Farm
  - type: battery
    energy_capacity: 2000
    power: 1000
  # - type: battery
  #   energy_capacity: 100
  #   power: 750
grid:
  name: Grid
subrewards:
  CO2:
    active: false
    scaling_factor: 1
  NE:
    active: false
    scaling_factor: 1
  TEST:
    active: true
    scaling_factor: 1
replay_buffers:
  real_capacity: 10000
  model_capacity: 10000
WorldModel:
  lr: 0.0001
  weight_decay: 0.01
  beta_weights:
    pred: 1.0
    dyn: 1.0
    rep: 0.1
  gradient_clipping: 0.5
  free_bits: 1.0
  RSSM:
    clamp_lower: -5.0
    clamp_upper: 5.0
    Encoder:
      clamp_lower: -5.0
      clamp_upper: 5.0
ActorCritic:
  actor_lr: 0.0001
  critic_lr: 0.0001
  actor_weight_decay: 0.01
  critic_weight_decay: 0.01
  gamma: 0.997
  lambda: 0.95
  ema_decay: 0.95
  entropy_coef: 0.05
