algorithm: Dreamer
chunk_size: 1000
training_steps: 20000
num_initial_random_steps: 200
update_interval: 50
batch_size: 32
agents:
  # - type: solar
  #   AC: 9000
  #   DC: 10000
  #   orientation: S
  - type: solar
    AC: 5000
    DC: 5500
    orientation: EW
  # - type: wind
  #   location: Onshore
  #   power: 1000
  #   AC: 900
  # - type: demand
  #   scale: 4.5
  #   profile: Farm
  - type: demand
    scale: 15
    profile: Farm
  - type: battery
    energy_capacity: 2000
    power: 1000
  # - type: battery
  #   energy_capacity: 100
  #   power: 750
grid:
  name: Grid
subrewards:
  CO2:
    active: true
    scaling_factor: 0.00002
replay_buffers:
  real_capacity: 100000
  model_capacity: 100000
