algorithm: Priorities
chunk_size: 1000
training_steps: 10000
num_initial_random_steps: 400
update_interval: 50
horizon: 8
batch_size: 32
update_steps: 2
deterministic: False
agents:
  # - type: solar
  #   AC: 9000
  #   DC: 10000
  #   orientation: S
  - type: solar
    AC: 2000
    DC: 2000
    orientation: EW
    trainable: true
  - type: solar
    AC: 1000
    DC: 1000
    orientation: EW
    trainable: true
  # - type: wind
  #   location: Onshore
  #   power: 1000
  #   AC: 900
  - type: demand
    scale: 15
    profile: Farm
    trainable: false
  - type: battery
    energy_capacity: 2000
    power: 1000
    trainable: true
  # - type: battery
  #   energy_capacity: 100
  #   power: 750
grid:
  name: Grid
subrewards:
  CO2:
    active: false
    scaling_factor: 1
  NE:
    active: false
    scaling_factor: 1
  TEST:
    active: true
    scaling_factor: 1
replay_buffers:
  real_capacity: 3000
  model_capacity: 3000
WorldModel:
  lr: 0.001
  weight_decay: 0.0
  beta_weights:
    pred: 1.0
    dyn: 1.0
    rep: 0.1
  clip_grad: 5
  free_bits: 1.0
  RSSM:
    clamp_lower: -5.0
    clamp_upper: 5.0
    LayerDetails:
      recurrent_size: 64
      latent_size: 32
      batch_first: True
      bias: True
      dropout: 0.0
      bidirectional: False
      num_layers: 2
    Encoder:
      clamp_lower: -5.0
      clamp_upper: 5.0
ActorCritic:
  actor_lr: 0.001
  critic_lr: 0.001
  actor_weight_decay: 0.0
  critic_weight_decay: 0.0
  actor_clip_grad: 5
  critic_clip_grad: 5
  gamma: 0.997
  lambda: 0.95
  ema_update: 0.98 # update the target networks with this factor
  s_ema_alpha: 0.9
  entropy_coef: 0.01 # coefficient for the entropy loss
