algorithm: Dreamer
chunk_size: 1000
training_steps: 20000
num_initial_random_steps: 600
update_interval: 50
horizon: 8
batch_size: 64
update_steps: 5
agents:
  # - type: solar
  #   AC: 9000
  #   DC: 10000
  #   orientation: S
  - type: solar
    AC: 2000
    DC: 2000
    orientation: EW
  - type: solar
    AC: 1000
    DC: 1000
    orientation: EW
  # - type: wind
  #   location: Onshore
  #   power: 1000
  #   AC: 900
  - type: demand
    scale: 15
    profile: Farm
  - type: battery
    energy_capacity: 2000
    power: 1000
  # - type: battery
  #   energy_capacity: 100
  #   power: 750
grid:
  name: Grid
subrewards:
  CO2:
    active: true
    scaling_factor: 1
replay_buffers:
  real_capacity: 10000
  model_capacity: 10000
