SAC:
  actor_hidden_dim: 64
  actor_lr: 8.542917132975773e-06
  alpha: 0.05
  alpha_lr: 3.6324045971121576e-05
  critic_actor_update_ratio: 2
  critic_lr: 9.583298937622828e-05
  eps: 1.0e-07
  gamma: 0.99
  hidden_dim: 128
  log_std_max: 2
  log_std_min: -5
  num_layers: 2
  tau: 0.025
  value_lr: 2.3747865429790834e-05
  weight_decay: 2.0179269817929525e-08
WorldModel:
  agent_enc_dim: 8
  agent_hidden_size: 32
  forecast_hidden_layers: 1
  forecast_hidden_size: 16
  lr: 0.001
  weight_decay: 0.0
  world_dynamics_hidden_size: 64
  world_enc_dim: 32
  world_hidden_size: 64
agents:
- AC: 2000
  DC: 2000
  orientation: EW
  trainable: false
  type: solar
- AC: 1000
  DC: 1000
  orientation: EW
  trainable: false
  type: solar
- profile: Farm
  scale: 15
  trainable: false
  type: demand
- energy_capacity: 2000
  power: 1000
  type: battery
  trainable: true
algorithm: Dyna
batch_size: 128
chunk_size: 2000
dyna:
  k: 6
  real_sample_ratio: 0.8
  sCTCE: false
  update_interval: 10
  updates_per_step: 18
  world_model_update_frequency: 1
grid:
  name: Grid
num_initial_random_steps: 2000
replay_buffers:
  model_capacity: 100000
  real_capacity: 100000
subrewards:
  CO2:
    active: false
    scaling_factor: 1
  NE:
    active: false
    scaling_factor: 1
  SS:
    active: false
    scaling_factor: 1
  BA:
    active: true
    scaling_factor: 1
training_steps: 30000
