algorithm: Priorities
agents:
  - type: solar
    AC: 9000
    DC: 10000
    orientation: EW
  - type: wind
    location: Onshore
    power: 3000
    AC: 2000
  - type: demand
    scale: 15
    profile: Farm
  - type: battery
    energy_capacity: 2000
    power: 1200
grid:
  name: Grid
