algorithm: Priorities
agents:
  - type: solar
    AC: 9000
    DC: 10000
    orientation: EW
  - type: wind
    location: Onshore
    power: 3000
    AC: 2000
  - type: demand
    scale: 9.5
    profile: Farm
  - type: battery
    energy_capacity: 1000
    power: 500
grid:
  name: Grid
