name: Run Tests

on:
  pull_request:
    branches:
      - dev  # Trigger only on PRs targeting the dev branch
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python with the required version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match the version in your pyproject.toml

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Step 4: Configure Poetry environment
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: |
          poetry install --no-root

      # Step 6: Run Pytest
      - name: Run Pytest
        run: |
          poetry run pytest --junitxml=pytest-results.xml
