name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python with the required version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match the version in your pyproject.toml

      # Step 3: Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Step 4: Configure Poetry
      - name: Configure Poetry
        run: |
          poetry config repositories.repowered ${{ secrets.PRIVATE_PYPI_URL}}
          poetry config http-basic.repowered ${{ secrets.PRIVATE_PYPI_USER }} ${{ secrets.PRIVATE_PYPI_PASSWORD}}


      # Step 5: Install dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      # Step 6: Install root
      - name: Install root
        run: poetry install --no-interaction

      # Step 7: Run Pytest
      - name: Run Pytest
        run: |
          poetry run coverage run --source='.'  -m pytest
